name: CI/CD - Iris Classification Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r api/requirements.txt
          pip install -r model/requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest api/test_api.py

      - name: Build the Docker image
        run: docker-compose build

      - name: Test the Docker image (optional)
        run: |
          docker-compose up -d
          sleep 10 # Дать время контейнерам запуститься
          # Добавьте здесь тесты для проверки работоспособности API в контейнере
          # Например, отправьте запрос к /docs и проверьте ответ
          docker-compose down

      - name: Log in to Docker Hub (optional)
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image to Docker Hub (optional)
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
        run: |
          IMAGE_ID=$(docker-compose config --property services.fastapi.image)
          IMAGE_ID=$(echo "$IMAGE_ID" | tr -d '"') 
          IMAGE_TAG=latest
          docker tag $IMAGE_ID ${{ secrets.DOCKER_USERNAME }}/iris-classification-fastapi:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/iris-classification-fastapi:$IMAGE_TAG
