name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.docker-buildkit
        key: docker-buildkit-${{ github.sha }}
        restore-keys: |
          docker-buildkit-

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker-build
      env:
        IMAGE_TAG: ${{ github.sha }}
        IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/my-app
      run: |
        docker buildx build --push \
          --cache-from type=local,dest=/tmp/.docker-buildkit \
          --cache-to type=local,dest=/tmp/.docker-buildkit \
          -t ${{ env.IMAGE_NAME }}:${IMAGE_TAG} .

    - name: Image digest
      run: echo "Image digest:${{ steps.docker-build.outputs.digest }}"
